### ISSUE TITLE
MetaInfo - Item: Usage  (not useful)

### ISSUE THREAD

**Issue by Tdannen** [QuantLet/Styleguide-and-FAQ#1]
The Usage Item of the MetaInfo adds no additional information to the QuantLet. In most cases it contains redundant information which is not preferable. Therefore, I would suggest to ignore/delete that field in all upcoming new QuantLets and integrate that piece of information (if not redundant) in the description tag or the input/output tag.

**Comment by lborke** [comment]
I completely agree!
