### ISSUE TITLE
Styleguide - FormatR package - question

### ISSUE THREAD

**Issue by polarstern** [QuantLet/Styleguide-and-FAQ#15]
tidy_source(source = "input.R", indent = 2, width.cutoff = 80, file = "output.R")
tidy_source(indent = 2, width.cutoff = 80, file = "output.R")

What for to mention these two examples, if you recommend to use the third one?
 tidy_source(file = "output.R")
-  Now it's unclear which style should be chosen and why (e.g. indent = 2 as at ex.1, or indent=4 by default at ex.3)
- If smb chooses ex.1 or ex.2, then he'll use the style with indent = 2 (instead of indent=4 which we use now)

I think it'd be better to suggest two options:
- main: 
  tidy_source(file = "output.R")
- optional - if smb wants to read it from file:
  tidy_source(source = "input.R", file = "output.R")

**Comment by lborke** [comment]
Makes sense!
@Tdannen : do you agree?

**Comment by polarstern** [comment]
... And?

**Comment by lborke** [comment]
We will finish that this week...

**Comment by lborke** [comment]
I have adjusted the text now. Plz check and make comments if necessary.

**Comment by polarstern** [comment]
It's fine now.
