### ISSUE TITLE
yaml list format

### ISSUE THREAD

**Issue by anastasia-stepanchenko** [QuantLet/Styleguide-and-FAQ#19]
**Hey guys, you write that these 2 alternatives are equal:**

Keywords:  financial, portfolio, returns, asset, time-series, plot
Keywords:     
- financial
- portfolio
- returns
- asset
- time-series
- plot

**I think they are not, the first alternative should be put into [...] like this:**
Keywords: [financial, portfolio, returns, asset, time-series, plot]

**Comment by lborke** [comment]
Thanks for the remark!

BUT the two alternatives are really equal in the sense that we ONLY need separate data fields.

Keywords: [financial, portfolio, returns, asset, time-series, plot]
would work, too. And additionally deliver an array with 6 items, namely the keywords.

For us it does not matter if the data fields are strings or array of strings.
Every transformation can be processed by one line of code once the YAML notation has been succesfully accepted by the YAML parser.
