### ISSUE TITLE
PDF doesn't work/open after download

### ISSUE THREAD

**Issue by lborke** [QuantLet/Styleguide-and-FAQ#8]
Please check if the file was correctly compliled. It does not work on my PC after downloading.

**Comment by Tdannen** [comment]
Lukas, ich verstehe nicht.

Wenn du die tex.datei in deinem latex tool einliest und dann compilen tust, müsste es doch gehen. Schließlich ist es nur code.

Oder versteh ich hier was falsch.

**Comment by lborke** [comment]
Ich meinte, dass die PDF-Datei nach dem Runterladen aus dem Repo nicht angezeigt werden konnte.
Diese neue PDF geht.
Die Latex-Datei habe ich jetzt auch erfolgreich getestet. Sie wird erfolgreich ohne Probleme kompiliert.

Also, ich meinte zuvor:
Die PDF-Datei ging nicht, falls jemand diese direkt anschauen wollte.
Jetzt ist alles ok :-)
